### ISSUE TITLE
Feature Request: add HierarchicalStateMachine type to TypeScript definitions 

### ISSUE THREAD

**Issue by aoberoi** [nickuraltsev/fluent-state-machine#29]
hello there 👋 

first of all, i just wanted to express my gratitude for this project. i think the API is great, the code is readable/understandable, and the functionality is complete and robust.

i'm using this package in a TypeScript project. I need to do something like the following, but TypeScript is giving me the error shown:

```
if (stateMachine.getCurrentState() === 'some_state' &&
    stateMachine.getStateHeirarchy !== undefined && stateMachine.getStateHeirarchy()[1] === 'some_substate') {
  // do stuff
}
```

TypeScript error:
```
[ts] Property 'getStateHierarchy' does not exist on type 'StateMachine<string, string>'.
```

the simplest fix i could think of would just be to export the interface for `HierarchicalStateMachine` so that after the `stateMachine.getStateHeirarchy !== undefined` condition, i could cast my `stateMachine` to that type specifically. i don't know if there's a more advanced technique for expressing true polymorphism in TypeScript.

edit: on closer inspection, it looks like the `StateMachineConfigurator.start()` method always returns a `HierarchicalStateMachine`, so maybe its just a matter of replacing the `StateMachine` type with the former in the definitions.

thanks!

**Comment by nickuraltsev** [comment]
Hi @aoberoi, 

Thank you for your kind words!

I think we can simply add `getStateHierarchy` to the `StateMachine` type in the definition file. We don't have to rename `StateMachine` to `HierarchicalStateMachine` and I think it would be a breaking change.

Would you be interested in submitting a PR for this?

**Comment by aoberoi** [comment]
@nickuraltsev: that sounds good to me! PR inbound :)
